#!name=Spotify(iOS15)
#!desc=部分解锁premium,建议重新登录,音质不能设置为超高
# 1. 搜索界面 歌单/歌曲可以随意切换完全播放  2. 音乐库已点赞歌曲随意切换完全播放

[Rule]
DOMAIN,audio4-ak-spotify-com.akamaized.net,香港
DOMAIN,cdn-spotify-experiments.conductrics.com,香港
DOMAIN,heads-ak-spotify-com.akamaized.net,香港
DOMAIN,spotify.com.edgesuite.net,香港
DOMAIN,spotify.map.fastly.net,香港
DOMAIN,spotify.map.fastlylb.net,香港
DOMAIN-SUFFIX,audio-ak-spotify-com.akamaized.net,香港
DOMAIN-SUFFIX,byspotify.com,香港
DOMAIN-SUFFIX,heads4-ak-spotify-com.akamaized.net,香港
DOMAIN-SUFFIX,pscdn.co,香港
DOMAIN-SUFFIX,scdn.co,香港
DOMAIN-SUFFIX,spoti.fi,香港
DOMAIN-SUFFIX,spotify-com.akamaized.net,香港
DOMAIN-SUFFIX,spotify-everywhere.com,香港
DOMAIN-SUFFIX,spotify.com,香港
DOMAIN-SUFFIX,spotify.design,香港
DOMAIN-SUFFIX,spotifycdn.com,香港
DOMAIN-SUFFIX,spotifycdn.net,香港
DOMAIN-SUFFIX,spotifycharts.com,香港
DOMAIN-SUFFIX,spotifycodes.com,香港
DOMAIN-SUFFIX,spotifyforbrands.com,香港
DOMAIN-SUFFIX,spotifyjobs.com,香港
DOMAIN-SUFFIX,spotifynewsroom.jp,香港
DOMAIN-SUFFIX,spotilocal.com,香港
DOMAIN-SUFFIX,tospotify.com,香港
DOMAIN-KEYWORD,-spotify-,香港
DOMAIN-KEYWORD,spotify.com,香港
USER-AGENT,Spotify*,香港
IP-CIDR,104.154.127.126/32,香港,no-resolve
IP-CIDR,35.186.224.47/32,香港,no-resolve

[MITM]
hostname = %APPEND% spclient.wg.spotify.com

[Script]
spotify-json = type=http-request,type=http-request,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,script-update-interval=0
