name: Merge EPG XML

on:
  push:
  schedule:
    - cron: "15 16,18,20,22,0,2,4,6,8,10,12,14 * * *"

jobs:
  merge-epg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet curl

      - name: Download and merge EPG
        run: |
          set -e
          TMPDIR=$(mktemp -d)
          DATE=$(TZ=Asia/Shanghai date +'%Y%m%d')
          
          #建立channel文件
          grep -o 'tvg-id="[^"]*"' iptv.m3u | cut -d'"' -f2 > $TMPDIR/channels.txt
          
          # 下载文件
          curl -s -o "$TMPDIR/1.xml" "https://epg.112114.xyz/pp.xml"
          curl -s -o "$TMPDIR/2.xml" "https://mytvsuperepg.860775.xyz/epg.xml"
          curl -s -o "$TMPDIR/3.xml" "https://epg.pw/api/epg.xml?lang=zh-hans&timezone=QXNpYS9TaGFuZ2hhaQ%3D%3D&date=$DATE&channel_id=410285"
          curl -s -o "$TMPDIR/4.xml" "https://epg.pw/api/epg.xml?lang=zh-hans&timezone=QXNpYS9TaGFuZ2hhaQ%3D%3D&date=$DATE&channel_id=410286"
          curl -s -o "$TMPDIR/5.xml" "https://epg.pw/api/epg.xml?lang=zh-hans&timezone=QXNpYS9TaGFuZ2hhaQ%3D%3D&date=$DATE&channel_id=370177"
          curl -s -o "$TMPDIR/6.xml" "https://epg.pw/api/epg.xml?lang=zh-hans&timezone=QXNpYS9TaGFuZ2hhaQ%3D%3D&date=$DATE&channel_id=410274"
          curl -s -o "$TMPDIR/7.xml" "https://epg.pw/api/epg.xml?lang=zh-hans&timezone=QXNpYS9TaGFuZ2hhaQ%3D%3D&date=$DATE&channel_id=410344"
          sed -i 2d "$TMPDIR/2.xml"
          
          # 初始化输出
          echo '<?xml version="1.0" encoding="UTF-8"?>' > epg.xml
          echo '<tv>' >> epg.xml
          # 按频道列表筛选
          while read -r ch; do
            [ -z "$ch" ] && continue
            echo "处理频道: $ch"
            for f in "$TMPDIR"/{1..7}.xml; do
              xmlstarlet sel -t -c "/tv/channel[@id='$ch']" "$f" >> epg.xml || true
              xmlstarlet sel -t -c "/tv/programme[@channel='$ch']" "$f" >> epg.xml || true
            done
          done < $TMPDIR/channels.txt
          echo '</tv>' >> epg.xml
          rm -rf "$TMPDIR"
          echo "合并完成 -> epg.xml"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add epg.xml
          git commit -m "EPG Update."
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
